package DBHelper;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;

/**
 * This is a super class that contains logic to establish connection to sqlite database and
 * perform queries with helper methods in the RaceCars class. It is used in tandem with RaceCarDBManager.
 * Its primary function is to support connection to the database and perform SQL queries.
 * <p>
 * Note: This code was generated by the SQLHelper plugin.
 *
 * @author SQLHelper
 **/
public class DBHelper {
	private String DATABASE_NAME;
	private Connection connection;
	private Statement statement;
	private ResultSet resultSet;

    /**
     * This constructor initializes DBHelper with no connections.
     */
	public DBHelper() {
		connection = null;
		statement = null;
		resultSet = null;
	}

    /**
     * This method sets the database name.
     * @param DATABASE_NAME name of the database
     */
    public void setDATABASE_NAME(String DATABASE_NAME) {
        this.DATABASE_NAME = DATABASE_NAME;
    }

    /**
     * This method performs connection to a database.
     * Note: No exceptions are thrown by method as they are handled by try and catch blocks.
     */
    private void connect() {
		try {
			Class.forName("org.sqlite.JDBC");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		try {
			connection = DriverManager.getConnection("jdbc:sqlite:" + DATABASE_NAME);
			statement = connection.createStatement();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

    /**
     * This method closes connection to the database.
     */
	private void close() {
		try {
			connection.close();
			statement.close();
			if (resultSet != null)
			resultSet.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

    /**
     * This method converts an array list of array lists to a 2D array.
     * @param list the array list to be converted
     * @return Object[][] the converted array list
     */
	private Object[][] arrayListTo2DArray(ArrayList<ArrayList<Object>> list) {
		Object[][] array = new Object[list.size()][];
		for (int i = 0; i < list.size(); i++) {
			ArrayList<Object> row = list.get(i);
			array[i] = row.toArray(new Object[row.size()]);
		}
		return array;
	}

    /**
     * This method performs a SQL query to the database.
     * @param sql the SQL statement to be executed
     */
	protected void execute(String sql) {
		try {
			connect();
			statement.execute(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		finally {
			close();
		}
	}

    /**
     * This method performs a SQL query and stores the result in a DefaultTableModel.
     * @param sql the SQL statement to be executed
     * @return DefaultTableModel stored result of the query
     */
	protected DefaultTableModel executeQueryToTable(String sql) {
		ArrayList<ArrayList<Object>> result = new ArrayList<ArrayList<Object>>();
		ArrayList<Object> columns = new ArrayList<Object>();
		connect();
		try {
			resultSet = statement.executeQuery(sql);
			int columnCount = resultSet.getMetaData().getColumnCount();
			for (int i = 1; i <= columnCount; i++)
			columns.add(resultSet.getMetaData().getColumnName(i));
			while (resultSet.next()) {
				ArrayList<Object> subresult = new ArrayList<Object>();
				for (int i = 1; i <= columnCount; i++)
				subresult.add(resultSet.getObject(i));
				result.add(subresult);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		close();
		return new DefaultTableModel(arrayListTo2DArray(result), columns.toArray());
	}

    /**
     * This method performs a SQL query and stores the result in an array list of objects.
     * @param sql the SQL statement to be executed
     * @return stored result of the query
     */
	protected ArrayList<ArrayList<Object>> executeQuery(String sql) {
		ArrayList<ArrayList<Object>> result = new ArrayList<ArrayList<Object>>();
		connect();
		try {
			resultSet = statement.executeQuery(sql);
			int columnCount = resultSet.getMetaData().getColumnCount();
			while (resultSet.next()) {
				ArrayList<Object> subresult = new ArrayList<Object>();
				for (int i = 1; i <= columnCount; i++) {
					subresult.add(resultSet.getObject(i));
				}
				result.add(subresult);
			}
		} catch (SQLException e){
			e.printStackTrace();
		}
		close();
		return result;
	}

}
