package DBHelper;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * This is a child class which contains generated code by SQLHelper to perform SQL action to
 * a sqlite database. It helps perform simple CRUD functions using SQL formatted code.
 * <p>
 * Note: This code was generated by the SQLHelper plugin.
 *
 * @author SQLHelper
 **/
public class RaceCars extends DBHelper {
	private final String TABLE_NAME = "RaceCars";
	public static final String VehicleID = "VehicleID";
	public static final String Make = "Make";
	public static final String Model = "Model";
	public static final String Year = "Year";
	public static final String TopSpeed = "TopSpeed";
	public static final String LaunchStatus = "LaunchStatus";

    /**
     * This method prepares a SQL select statement.
     * @param fields what table columns to select
     * @param whatField specified column to filter row
     * @param whatValue specified value to look for when filtering row
     * @param sortField what column to sort query by
     * @param sort sort condition
     * @return String a SQL select statement
     */
	private String prepareSQL(String fields, String whatField, String whatValue, String sortField, String sort) {
		String query = "SELECT ";
		query += fields == null ? " * FROM " + TABLE_NAME : fields + " FROM " + TABLE_NAME;
		query += whatField != null && whatValue != null ? " WHERE " + whatField + " = \"" + whatValue + "\"" : "";
		query += sort != null && sortField != null ? " order by " + sortField + " " + sort : "";
		return query;
	}

    /**
     * This method prepares and performs a SQL insert query.
     * @param VehicleID The id of the vehicle
     * @param Make The make of the vehicle
     * @param Model The model of the vehicle
     * @param Year The year that the vehicle was made
     * @param TopSpeed The top speed that vehicle can perform
     * @param LaunchStatus The integer value (0 or 1) of the launch status
     */
	public void insert(Integer VehicleID, String Make, String Model, Integer Year, Double TopSpeed, Integer LaunchStatus) {
		Make = Make != null ? "\"" + Make + "\"" : null;
		Model = Model != null ? "\"" + Model + "\"" : null;
		
		Object[] values_ar = {VehicleID, Make, Model, Year, TopSpeed, LaunchStatus};
		String[] fields_ar = {RaceCars.VehicleID, RaceCars.Make, RaceCars.Model, RaceCars.Year, RaceCars.TopSpeed, RaceCars.LaunchStatus};
		String values = "", fields = "";
		for (int i = 0; i < values_ar.length; i++) {
			if (values_ar[i] != null) {
				values += values_ar[i] + ", ";
				fields += fields_ar[i] + ", ";
			}
		}
		if (!values.isEmpty()) {
			values = values.substring(0, values.length() - 2);
			fields = fields.substring(0, fields.length() - 2);
			super.execute("INSERT INTO " + TABLE_NAME + "(" + fields + ") values(" + values + ");");
		}
	}

    /**
     * This method performs a SQL delete query.
     * @param whatField specified column to look at
     * @param whatValue specified value to filter row
     */
	public void delete(String whatField, String whatValue) {
		super.execute("DELETE from " + TABLE_NAME + " where " + whatField + " = " + whatValue + ";");
	}

    /**
     * This method performs a SQL update query.
     * @param whatField specified column to update
     * @param whatValue specified value of what to set
     * @param whereField specified column to look at
     * @param whereValue specified value to filter row
     */
	public void update(String whatField, String whatValue, String whereField, String whereValue) {
		super.execute("UPDATE " + TABLE_NAME + " set " + whatField + " = \"" + whatValue + "\" where " + whereField + " = \"" + whereValue + "\";");
	}

    /**
     * This method performs a SQL select query using the parent method prepareSQL and returns the result.
     * @param fields what table columns to select
     * @param whatField specified column to filter row
     * @param whatValue specified value to look for when filtering row
     * @param sortField what column to sort query by
     * @param sort sort condition
     * @return converted result of query into the form of an array list
     */
	public ArrayList<ArrayList<Object>> select(String fields, String whatField, String whatValue, String sortField, String sort) {
		return super.executeQuery(prepareSQL(fields, whatField, whatValue, sortField, sort));
	}

    /**
     * This method performs any SQL query using the parent method executeQuery and returns the result.
     * @param query the SQL statement the user would like to perform
     * @return converted result of the query into the form of an array list
     */
	public ArrayList<ArrayList<Object>> getExecuteResult(String query) {
		return super.executeQuery(query);
	}

    /**
     * This method simply performs any SQL query using the parent method execute.
     * @param query the SQL statement the user would like to perform.
     */
	public void execute(String query) {
		super.execute(query);
	}

    /**
     * This method performs a SQL select statement and returns the result as a DefaultTableModel.
     * @param fields what table columns to select
     * @param whatField specified column to filter row
     * @param whatValue specified value to look for when filtering row
     * @param sortField what column to sort query by
     * @param sort sort condition
     * @return DefaultTableModel stored result of select query as a table
     */
	public DefaultTableModel selectToTable(String fields, String whatField, String whatValue, String sortField, String sort) {
		return super.executeQueryToTable(prepareSQL(fields, whatField, whatValue, sortField, sort));
	}

}
